apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-nodeport
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080   # must be in the default range 30000-32767
