apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-clusterip
spec:
  type: ClusterIP
  selector:
    app: hello-k8s
  ports:
    - port: 80          # the Service's own virtual IP:port
      targetPort: 8080   # the container port to forward to
