apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-k8s
    tier: web
spec:
  containers:
    - name: hello-k8s
      image: localhost:5000/hello-k8s:1.0.0
      ports:
        - containerPort: 8080
      env:
        - name: GREETING
          value: "Hello from a declarative Pod!"
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
